---
- name: Updating new servers
  hosts: cdp_mid_may
  become: yes
  ignore_errors: yes
  gather_facts: yes
  tasks: 
  - name: Backing up files in repos.d
    copy:
      src: /etc/yum.repos.d/redhat.repo
      dest: /etc/yum.repos.d/redhat.repo.backup

  - name: removing redhat repo
    shell: rm /etc/yum.repos.d/redhat.repo
    
  - name: echoing and redirecting
    shell: echo "sslverify=false" >> /etc/yum.conf

  - name: copying rhel8 build repo
    copy:
      src: /mnt/post_install/new_build/local.repo
      dest: /etc/yum.repos.d/

  - name: installing nfs
    shell: yum -y install nfs-utils

  - name: starting nfs
    service:
      name: nfs-server
      state: started
      enabled: yes  
  
  - name: Running update on Targets.
    shell: yum -y update

  - name: 
    copy:
      src: /etc/resolv.conf
      dest: /etc/resolv.conf

...     
