---
- name: resizing filesystem
  hosts: cdp_may
  become: yes
  ignore_errors: yes
  gather_facts: yes
  tasks:

    - name: resize / to make it 64G
      lvol:
        vg: vg_sda
        lv: lv_root
        size: 64G
        resizefs: true

    - name: resize /var to make it 128.G
      lvol:
        vg: vg_sda
        lv: lv_var
        size: 128G
        resizefs: true

    - name: resize /opt to mke it 64G
      lvol:
        vg: vg_sda
        lv: lv_opt
        size: 64G
        resizefs: true

    - name: resize /tmp to make it 48G
      lvol:
        vg: vg_sda
        lv: lv_tmp
        size: 48G
        resizefs: true

    - name: resize /opt/cloudera to make it 64G
      lvol:
        vg: vg_sda
        lv: lv_opt_IBM_ITM
        size: 64G
        resizefs: true

    - name: resize /home to make it 128G
      lvol:
        vg: vg_sda
        lv: lv_local_home
        size: 128G
        resizefs: true

...

